// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWlZFvXjblRnY2eA-nqrO99pzJ3g4lfM',
    appId: '1:782266172302:web:9c043175449eef1fd0dadf',
    messagingSenderId: '782266172302',
    projectId: 'fir-fa445',
    authDomain: 'fir-fa445.firebaseapp.com',
    databaseURL: 'https://fir-fa445-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fa445.appspot.com',
    measurementId: 'G-5QNB5RW8KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkgfuN1-a0Nf9j5UGED_ob48v3S71BqTs',
    appId: '1:782266172302:android:9b2b2c3adf0513a6d0dadf',
    messagingSenderId: '782266172302',
    projectId: 'fir-fa445',
    databaseURL: 'https://fir-fa445-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fa445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC52IAN0iThhG5EK-IuGLnvOD_J9ljdEkA',
    appId: '1:782266172302:ios:33fefdb0d721ccadd0dadf',
    messagingSenderId: '782266172302',
    projectId: 'fir-fa445',
    databaseURL: 'https://fir-fa445-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fa445.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC52IAN0iThhG5EK-IuGLnvOD_J9ljdEkA',
    appId: '1:782266172302:ios:33fefdb0d721ccadd0dadf',
    messagingSenderId: '782266172302',
    projectId: 'fir-fa445',
    databaseURL: 'https://fir-fa445-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fa445.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAWlZFvXjblRnY2eA-nqrO99pzJ3g4lfM',
    appId: '1:782266172302:web:f78d0ce8f52b5d30d0dadf',
    messagingSenderId: '782266172302',
    projectId: 'fir-fa445',
    authDomain: 'fir-fa445.firebaseapp.com',
    databaseURL: 'https://fir-fa445-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fa445.appspot.com',
    measurementId: 'G-J0FM2CBH62',
  );
}
